(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'auth_user' is not defined"
p3
sS'layer'
p4
S'/media/Volume2/web2py/applications/scrumLite/controllers/createteam.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# try something like\n@auth.requires_login()\ndef createteam():\n        form = SQLFORM(db.Team)\n        if form.process().accepted:\n            group_id = auth.add_group(form.vars.Team_Name, form.vars.Product_Description)\n            auth.add_membership(auth_user.id, group_id)\n        elif form.errors:\n            response.flash = 'form is invalid'\n        return dict(form=form)\n\nresponse._vars=response._caller(createteam)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/media/Volume2/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/media/Volume2/web2py/applications/scrumLite/controllers/createteam.py", line 13, in <module>\n  File "/media/Volume2/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/media/Volume2/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/media/Volume2/web2py/applications/scrumLite/controllers/createteam.py", line 8, in createteam\n    auth.add_membership(auth_user.id, group_id)\nNameError: global name \'auth_user\' is not defined\n'
p11
s.